module.exports = {
  apps: [
    {
      name: 'fincoll-server',
      script: '/home/rford/caelum/ss/fincoll/.venv/bin/python',
      args: '-m fincoll.server',
      cwd: '/home/rford/caelum/ss/fincoll',
      interpreter: 'none',
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      env: {
        PYTHONUNBUFFERED: '1',
        FINCOLL_HOST: '0.0.0.0',
        FINCOLL_PORT: '8001',
        V5_INFERENCE_URL: 'http://10.32.3.62:5000',
      },
      error_file: '/home/rford/caelum/ss/logs/fincoll_error.log',
      out_file: '/home/rford/caelum/ss/logs/fincoll_out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
    },
    {
      name: 'paper-trading-v5',
      script: '/home/rford/caelum/ss/finvec/.venv/bin/python',
      args: 'paper_trading_bot_v5.py',
      cwd: '/home/rford/caelum/ss/finvec',
      interpreter: 'none',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        PYTHONUNBUFFERED: '1',
      },
      error_file: '/home/rford/caelum/ss/logs/paper_trading_v5_error.log',
      out_file: '/home/rford/caelum/ss/logs/paper_trading_v5_out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
    },
  ],
};
